capitole_admitere = [
    "Introducere în anatomie şi fiziologie: Niveluri de organizare structurală",
    "Introducere în anatomie şi fiziologie: Caracteristici ale organismului uman",
    "Introducere în anatomie şi fiziologie: Termeni direcționali",
    "Introducere în anatomie şi fiziologie: Cavitățile și regiunile corpului",
    "Celulele şi fiziologia celulară: Structura celulei", 
    "Celulele şi fiziologia celulară: Celulele și energia",
    "Celulele şi fiziologia celulară: Mitoza și reproducerea celulei",
    "Celulele şi fiziologia celulară: Sinteza proteică",
    "Oasele si articulatiile",
    "Ţesutul muscular: Mușchiul striat scheletic",
    "Ţesutul muscular: Energia necesară contracției musculare",
    "Ţesutul muscular: Funcțiile mușchiului neted și cardiac",
    "Ţesutul nervos: Organizare",
    "Ţesutul nervos: Fiziologia nervilor",
    "Organizarea sistemului nervos: Sistemul nervos central",
    "Organizarea sistemului nervos: Sistemul nervos periferic",
    "Organele de simt: Ochiul",
    "Organele de simt: Urechea",
    "Organele de simt: organe de simt exceptand ochiul si urechea",
    "Sistemul endocrin: Hipofiza",
    "Sistemul endocrin: Glanda tiroidă",
    "Sistemul endocrin: Glandele paratiroide",
    "Sistemul endocrin: Pancreasul",
    "Sistemul endocrin: Glandele suprarenale",
    "Sângele: Plasma",
    "Sângele: Globulele roșii",
    "Sângele: Globulele albe",
    "Sângele: Plachetele sanguine",
    "Sistemul cardiovascular: Inima",
    "Sistemul cardiovascular: Vasele sanguine",
    "Sistemul respirator: Anatomia sistemului respirator",
    "Sistemul respirator: Fiziologia respirației",
    "Sistemul digestiv: Tractul gastrointestinal", 
    "Sistemul digestiv: Organele anexe", 
    "Sistemul limfatic şi imun",
    "Metabolism și nutriție",
    "Sistemul urinar: Rinichii",
    "Sistemul urinar: Organe anexe",
    "Sistemul reproducător masculin: Testiculele",
    "Sistemul reproducător masculin: Ducte și organe anexe",
    "Sistemul reproducător masculin: Hormonii masculini",
    "Sistemul reproducător feminin: Ovarele și organele anexe",
    "Sistemul reproducător feminin: Fiziologia reproducerii la femeie",
    "Sistemul reproducător feminin: Dezvoltarea embrionară și fetală"
    ]
capitole_bac_biologie_vegetala = [
    "Virusuri: caractere generale, clasificare: adenovirusuri, ribovirusuri, exemple la om",
    "Regnurile lumii vii: clasificare, caracterizare generala: la fiecare grup se prezinti caractere de regn, increngatura, \
        clase, legate de mediul si modul de viati, morfologie, tipul de locomotie, de nutritie, de respiratie, de \
        reproducere (fara cicluri evolutive), important& si exemple reprezentative",
    "Conservarea biodiversităţii în România",
    "Structura, ultrastructura şi rolul componentelor celulei: procariote: structura; \
        eucariote: - invelisul celului, - citoplasma, - nucleu",
    "Diviziunea celulară: importanti, clasificare: ciclul celular, mitoza, meioza, indirecta, cromozomi si fus de diviziune",
    "Ereditatea si variabilitatea lumii vii: Concepte: ereditate, variabilitate.",
    "Mecanismele de transmitere a caracterelor ereditare - legile mendeliene şi abateri de la segregarea mendeliană - codominanţa",
    "Teoria cromozomială a eredităţii",
    "Determinismul cromozomial al sexelor",
    "Influenţa mediului asupra eredităţii",
    "Genetică umană: boli ereditare – clasificare şi exemple",
    "Ţesuturi vegetale",
    "Ţesuturi animale",
    "Nutriţia în lumea vie",
    "Nutritia la animale",
    "Heterotrofia la fungii",
    "Nutritia simbionta si nutritia mixta",
    "Glandele anexe ale tubului digestiv",
    "Boli ale sistemului digestiv la om",
    "Respiraţia în lumea vie",
    "Respirația la plante",
    "Respirația la animale",
    "Boli ale sistemului respirator la om",
    "Circulaţia la plante",
    "Mediul intern la mamifere",
    "Excreţia la plante",
    "Excreția la animale",
    "Boli ale sistemului excretor la om",
    "Sensibilitatea şi mişcarea la plante",
    "Sensibilitatea la animale (organe de simţ la mamifere)",
    "Sistemul nervos la mamifere",
    "Boli ale sistemului nervos central la om",
    "Locomoţia la animale",
    "Reproducerea la plante: Reproducerea asexuata la plante: specializata si vegetativa",
    "Reproducerea la plante: Reproducerea sexuala la angiosperme: floare - structura; fecundatie; samanta - alcatuire; \
        fruct - tipuri reprezentative de fructe",
    "Reproducerea la om: Sistemul reproducator femel si sistemul reproducator mascul (localizare, structurii si rol)",
    "Reproducerea la om: Boli cu transmitere secuala (sifilis, gonoree, candidoza, SIDA) - manifestari, cauze si prevenire"
]
capitole_bac_anatomie_genetica = [
    "Alcatuirea corpului uman: topografia organelor şi a sistemelor de organe",
    "Alcatuirea corpului uman: planuri şi raporturi anatomice",
    "Sistemul nervos: clasificarea sistemului nervos din punct de vedere topografic şi funcţional",
    "Sistemul nervos: sistemul nervos somatic: funcţia reflexă - actul reflex, funcţia de conducere - clasificarea căilor de conducere si rolul acestora",
    "Sistemul nervos vegetativ - clasificare, efecte ale stimulării simpaticului şi parasimpaticului",
    "Sistemul nervos: noţiuni elementare de igienă şi de patologie: meningită, comă, hemoragii cerebrale",
    "Analizatori: segmentele unui analizator",
    "Analizatori: fiziologia analizatorilor: vizual, auditiv, vestibular, cutanat",
    "Analizatori: noţiuni elementare de igienă şi patologie: herpes, cataractă, glaucom, conjunctivită, otită",
    "Glande endocrine: topografie, hormoni",
    "Glande endocrine: efecte definitorii: hipofiză, tiroidă, pancreas, suprarenale, gonade",
    "Glande endocrine: disfuncţii (nanism hipofizar, gigantism, acromegalie, diabet insipid, boala Basedow-Graves, mixedem, nanism tiroidian, guşă endemică, diabet zaharat)",
    "Sistemul osos: scheletul - alcătuire, rol, creşterea în lungime şi în grosime a oaselor",
    "Sistemul osos: noţiuni elementare de igienă şi patologie: deformări, fracturi, entorse, luxaţii",
    "Sistemul muscular: muşchi scheletici: principalele grupe, tipuri de contracţii",
    "Sistemul muscular: noţiuni elementare de igienă şi de patologie: oboseală musculară, întinderi şi rupturi musculare",
    "Digestia si absorbtia: transformări fizico-chimice ale alimentelor în tubul digestiv",
    "Digestia si absorbtia: absorbţia intestinală",
    "Digestia si absorbtia: fiziologia intestinului gros",
    "Digestia si absorbtia: noţiuni elementare de igienă şi patologie: carii dentare, stomatită, enterocolite, ciroză hepatică, litiază biliară, pancreatită",
    "Circulatia: grupe sanguine, imunitate",
    "Circulatia: activitatea cardiacă, parametri funcţionali - frecvenţă cardiacă, debit cardiac, tensiune arterială, puls arterial",
    "Circulatia: circulaţia mare şi mică",
    "Circulatia: noţiuni elementare de igienă şi patologie: cardiopatie ischemică, hemoragii interne şi externe, leucemii, anemii",
    "Respiratia: ventilaţia pulmonară, transportul gazelor, schimbul de gaze, volume şi capacităţi respiratorii",
    "Respiratia: noţiuni elementare de igienă şi patologie: gripă, fibroză pulmonară, emfizem",
    "Excretia: formarea şi eliminarea urinei",
    "Excretia: noţiuni elementare de igienă şi de patologie: cistită, nefrită, glomerulonefrită",
    "Functia de reproducere: sistemul reproducător: componente, fiziologie",
    "Functia de reproducere: sănătatea reproducerii: planificare familială, concepţie şi contracepţie, sarcina şi naşterea",
    "Functia de reproducere: noţiuni elementare de igienă şi de patologie: anexită, adenom de prostată",
    "Genetica moleculara - Acizi nucleici: compoziţia chimică",
    "Genetica moleculara - Acizi nucleici: structura primară şi secundară a ADN",
    "Genetica moleculara - Acizi nucleici: tipuri de ARN, structură şi funcţii",
    "Genetica moleculara - Acizi nucleici: funcţia autocatalitică şi heterocatalitică",
    "Genetica moleculara - Organizarea materialului genetic: la virusuri, procariote şi eucariote",
    "Genetica umana: Genomul uman: componentul cromozomial",
    "Genetica umana: mutageneza si teratogeneza: anomalii cromozomiale asociate cancerului uman (fenotipul cancerului, agenți carcinogeni)",
    "Genetica umana: sfaturi genetice",
    "Genetica umana: diagnosticul prenatal",
    "Genetica umana: fertilizarea in vitro",
    "Genetica umana: clonarea terapeutică",
    "Genetica umana: terapia genică",
    "Ecologie umana: particularități ale biotopului și biocenozei",
    "Ecologie umana: relații interspecifice în ecosistemele antropizate",
    "Impactul antropic asupra ecosistemelor naturale: degradarea habitatelor",
    "Impactul antropic asupra ecosistemelor naturale: introducerea de specii noi",
    "Impactul antropic asupra ecosistemelor naturale: supraexploatarea resurselor biologice (defrișsare, pățunat, pescuit, vânătoare)",
    "Impactul antropic asupra ecosistemelor naturale: urbanizare şi industrializare",
    "Impactul antropic asupra ecosistemelor naturale: deteriorarea mediului prin poluare chimică, fizică, biologică"
]
